# Generated by Django 5.0.7 on 2024-08-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concourphy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('annee', models.IntegerField()),
                ('filier', models.CharField(max_length=10)),
                ('epreuve', models.CharField(max_length=10)),
            ],
        ),
    ]
