# Generated by Django 5.0.7 on 2024-08-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourphy',
            name='corrige',
            field=models.FileField(blank=True, null=True, upload_to='corrige/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='concourphy',
            name='electromagnetisme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concourphy',
            name='electronique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concourphy',
            name='mecanique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concourphy',
            name='numepreuve',
            field=models.CharField(choices=[('physique 1', 'physique 1'), ('physique 2', 'physique 2')], default='physique 1', max_length=10),
        ),
        migrations.AddField(
            model_name='concourphy',
            name='optique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concourphy',
            name='quantique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concourphy',
            name='thermodynamique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='concourphy',
            name='epreuve',
            field=models.FileField(blank=True, null=True, upload_to='epreuve/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='concourphy',
            name='filier',
            field=models.CharField(choices=[('MP', 'MP'), ('PSI', 'PSI'), ('TSI', 'TSI')], default='MP', max_length=10),
        ),
        migrations.AlterField(
            model_name='concourphy',
            name='nom',
            field=models.CharField(choices=[('CNC', 'CNC'), ('E3A', 'E3A'), ('X - ENS', 'X - ENS'), ('Mines ponts', 'Mines ponts'), ('Centrale', 'Centrale')], default='CNC', max_length=15),
        ),
    ]
