# Generated by Django 5.0.7 on 2024-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concour', '0005_alter_concourphy_corrige_alter_concourphy_epreuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concourphy',
            name='corrige',
            field=models.FileField(blank=True, null=True, upload_to='corrige/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='concourphy',
            name='epreuve',
            field=models.FileField(blank=True, null=True, upload_to='epreuve/%Y/%m/%d'),
        ),
    ]
