# Generated by Django 5.0.7 on 2024-10-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concour', '0007_concourchimie_concourmath'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourchimie',
            name='details',
            field=models.CharField(default='Détails non fournis', max_length=200),
        ),
        migrations.AddField(
            model_name='concourmath',
            name='details',
            field=models.CharField(default='Détails non fournis', max_length=200),
        ),
        migrations.AddField(
            model_name='concourphy',
            name='details',
            field=models.CharField(default='Détails non fournis', max_length=200),
        ),
    ]
