# Generated by Django 5.0.7 on 2025-02-09 12:48

import Concour.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concour', '0008_concourchimie_details_concourmath_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concourchimie',
            name='corrige',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='corriges/chimie/%Y', validators=[Concour.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='concourchimie',
            name='epreuve',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='epreuves/chimie/%Y', validators=[Concour.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='concourmath',
            name='corrige',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='corriges/math/%Y', validators=[Concour.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='concourmath',
            name='epreuve',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='epreuves/math/%Y', validators=[Concour.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='concourphy',
            name='corrige',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='corriges/physique/%Y', validators=[Concour.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='concourphy',
            name='epreuve',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='epreuves/physique/%Y', validators=[Concour.models.validate_pdf]),
        ),
    ]
